name: CI CD Node.js App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Run test
        run: npm test

      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          script: |
            cd /var/www/html/coop-api

            git pull origin main

            npm install

            pm2 start ecosystem.config.js