name: CI-CD coop-api

on:
  push:
    branches:
      - main

jobs:

  deploy:
    runs-on: self-hosted

    steps:

    - name: Checkout Source
      uses: actions/checkout@v4

    - name: Deploy Project
      run: |
        cd /var/www/html/coop-api/backend
        sh build/deploy.sh